package com.ustglobal.exception.customizedcheckedexception;

public class TestAmount {

	public static void main(String[] args) {

		System.out.println("Main started");
		
		ValidateAmount va = new ValidateAmount();
		try {
			va.checkAmount(20000);
		} catch (InvalidAmountException e) {
			e.printStackTrace();
		}
		
		System.out.println("Main ended");
	}

}
